"use client";

import { FormEvent, useState } from "react";

type Salon = Record<string, string | number | null>;
type Service = { id: number; title: string; description: string; icon: string; price: number; duration: number; isActive: boolean; isPopular: boolean; isBookable: boolean };
type Master = { id: number; name: string; role: string; experience: string; bio: string | null; image: string; tags: string; isActive: boolean; shifts: { dayOfWeek: number }[]; services: { serviceId: number }[] };

const days = [[1, "Пн"], [2, "Вт"], [3, "Ср"], [4, "Чт"], [5, "Пт"], [6, "Сб"], [0, "Вс"]] as const;

export function AdminCatalogEditor({ salon, services, masters }: { salon: Salon; services: Service[]; masters: Master[] }) {
  return <div className="catalog-layout"><SalonForm salon={salon} /><section className="admin-panel"><div className="admin-panel-head"><div><h2>Услуги</h2><p>Цены и длительность сразу обновляются на сайте, в записи и Android-приложении.</p></div></div><div className="catalog-grid">{services.map((service) => <ServiceForm key={service.id} service={service} />)}</div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Мастера и смены</h2><p>Укажите специализации и регулярные рабочие дни.</p></div></div><div className="catalog-master-list">{masters.map((master) => <MasterForm key={master.id} master={master} services={services} />)}</div></section></div>;
}

function SalonForm({ salon }: { salon: Salon }) {
  const [status, setStatus] = useState("");
  return <form className="admin-panel catalog-form" onSubmit={(event) => submitForm(event, "salon", setStatus)}><div className="admin-panel-head"><div><h2>Данные салона</h2><p>Контакты, тексты, часы работы и расположение публичной страницы.</p></div><SaveButton status={status} /></div><div className="catalog-fields"><Field name="name" label="Название" value={salon.name} /><Field name="subtitle" label="Подпись" value={salon.subtitle} /><Field name="tagline" label="Главный заголовок" value={salon.tagline} wide /><Field name="description" label="Описание" value={salon.description} wide textarea /><Field name="phone" label="Телефон" value={salon.phone} /><Field name="email" label="Email, если есть" value={salon.email} /><Field name="address" label="Адрес" value={salon.address} wide /><Field name="workingHoursStart" label="Будни: открытие" value={salon.workingHoursStart} /><Field name="workingHoursEnd" label="Будни: закрытие" value={salon.workingHoursEnd} /><Field name="weekendHoursStart" label="Выходные: открытие" value={salon.weekendHoursStart} /><Field name="weekendHoursEnd" label="Выходные: закрытие" value={salon.weekendHoursEnd} /><Field name="latitude" label="Широта" value={salon.latitude} type="number" /><Field name="longitude" label="Долгота" value={salon.longitude} type="number" /><Field name="heroImage" label="URL главного фото" value={salon.heroImage} wide /><Field name="aboutImage" label="URL фото о студии" value={salon.aboutImage} wide /><Field name="vkUrl" label="VK" value={salon.vkUrl} /><Field name="telegramUrl" label="Telegram" value={salon.telegramUrl} /><Field name="whatsappUrl" label="WhatsApp" value={salon.whatsappUrl} /><Field name="mapUrl" label="Яндекс.Карты" value={salon.mapUrl} /></div>{status && status !== "loading" ? <p className={`catalog-status ${status === "saved" ? "success" : "error"}`}>{status === "saved" ? "Изменения сохранены" : status}</p> : null}</form>;
}

function ServiceForm({ service }: { service: Service }) {
  const [status, setStatus] = useState("");
  return <form className="catalog-item" onSubmit={(event) => submitForm(event, "service", setStatus, service.id)}><div className="catalog-item-head"><span>{service.icon}</span><strong>{service.title}</strong></div><Field name="title" label="Название" value={service.title} /><Field name="description" label="Описание" value={service.description} textarea /><div className="catalog-inline"><Field name="price" label="Цена, ₽ (0 — по запросу)" value={service.price} type="number" /><Field name="duration" label="Минут" value={service.duration} type="number" /><Field name="icon" label="Иконка" value={service.icon} /></div><div className="catalog-checks"><Check name="isActive" label="Активна" checked={service.isActive} /><Check name="isPopular" label="На главной" checked={service.isPopular} /><Check name="isBookable" label="Доступна онлайн" checked={service.isBookable} /></div><SaveButton status={status} />{status && status !== "loading" && status !== "saved" ? <p className="catalog-status error">{status}</p> : null}</form>;
}

function MasterForm({ master, services }: { master: Master; services: Service[] }) {
  const [status, setStatus] = useState("");
  const selectedDays = new Set(master.shifts.map((shift) => shift.dayOfWeek));
  const selectedServices = new Set(master.services.map((service) => service.serviceId));
  return <form className="catalog-master" onSubmit={(event) => submitMaster(event, setStatus, master.id)}><img src={master.image} alt={master.name} /><div className="catalog-master-fields"><div className="catalog-inline"><Field name="name" label="Имя" value={master.name} /><Field name="role" label="Специализация" value={master.role} /><Field name="experience" label="Опыт" value={master.experience} /></div><Field name="bio" label="Коротко о мастере" value={master.bio} textarea /><Field name="image" label="URL фотографии" value={master.image} /><Field name="tags" label="Навыки через |" value={master.tags} /><fieldset><legend>Рабочие дни</legend><div className="catalog-checks">{days.map(([value, label]) => <Check key={value} name="workDays" value={value} label={label} checked={selectedDays.has(value)} />)}</div></fieldset><fieldset><legend>Выполняет услуги</legend><div className="catalog-checks">{services.map((service) => <Check key={service.id} name="serviceIds" value={service.id} label={service.title} checked={selectedServices.has(service.id)} />)}</div></fieldset><Check name="isActive" label="Мастер активен" checked={master.isActive} /><SaveButton status={status} />{status && status !== "loading" ? <p className={`catalog-status ${status === "saved" ? "success" : "error"}`}>{status === "saved" ? "Сохранено" : status}</p> : null}</div></form>;
}

function Field({ name, label, value, wide = false, textarea = false, type = "text" }: { name: string; label: string; value: unknown; wide?: boolean; textarea?: boolean; type?: string }) { return <label className={wide ? "wide" : ""}>{label}{textarea ? <textarea name={name} defaultValue={String(value ?? "")} rows={3} /> : <input name={name} type={type} step={type === "number" ? "any" : undefined} defaultValue={String(value ?? "")} />}</label>; }
function Check({ name, label, checked, value = "true" }: { name: string; label: string; checked: boolean; value?: string | number }) { return <label className="catalog-check"><input type="checkbox" name={name} value={value} defaultChecked={checked} /><span>{label}</span></label>; }
function SaveButton({ status }: { status: string }) { return <button className="button button-primary" type="submit" disabled={status === "loading"}>{status === "loading" ? "Сохраняем..." : "Сохранить"}</button>; }

async function submitForm(event: FormEvent<HTMLFormElement>, type: string, setStatus: (value: string) => void, id?: number) { event.preventDefault(); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form.entries()); setStatus("loading"); try { await send({ ...data, type, id, isActive: form.has("isActive"), isPopular: form.has("isPopular"), isBookable: form.has("isBookable") }); setStatus("saved"); } catch (error) { setStatus(error instanceof Error ? error.message : "Ошибка сохранения"); } }
async function submitMaster(event: FormEvent<HTMLFormElement>, setStatus: (value: string) => void, id: number) { event.preventDefault(); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form.entries()); setStatus("loading"); try { await send({ ...data, type: "master", id, isActive: form.has("isActive"), workDays: form.getAll("workDays").map(Number), serviceIds: form.getAll("serviceIds").map(Number) }); setStatus("saved"); } catch (error) { setStatus(error instanceof Error ? error.message : "Ошибка сохранения"); } }
async function send(data: Record<string, unknown>) { const response = await fetch("/api/admin/catalog", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Не удалось сохранить изменения"); }
